Repository Uni-Made/BE, pull requests merged in 2024-07, with the labels that each got.

#18 🌏 ci: ci/cd 파이프라인 구축 (#6)
  .gitignore
  appsec.yml
  scripts/start.sh
  scripts/stop.sh
Labels: :earth_asia: Ci

#20 🌏 [CI] ci/cd 파이프라인 구축 (#6)
  appspec.yml
Labels: :earth_asia: Ci

#26 :sparkles: [FEATURE] Products 엔티티 칼럼 추가(#24)
  src/main/java/umc/unimade/domain/orders/entity/PurchaseForm.java
  src/main/java/umc/unimade/domain/products/entity/PickupOption.java
  src/main/java/umc/unimade/domain/products/entity/Products.java
Labels: ✨ Feature

#23 :sparkles: [FEATURE] S3 설정 (#22)
  build.gradle
  src/main/java/umc/unimade/global/config/MultipartJackson2HttpMessageConverter.java
  src/main/java/umc/unimade/global/config/S3Config.java
  src/main/java/umc/unimade/global/util/s3/S3Provider.java
  src/main/java/umc/unimade/global/util/s3/dto/S3UploadRequest.java
Labels: ✨ Feature

#28 ✨ [FEATURE] 판매자 회원 요청, 상품 요청 테이블 분리 (#27)
  src/main/java/umc/unimade/domain/accounts/entity/Buyer.java
  src/main/java/umc/unimade/domain/accounts/entity/Seller.java
  src/main/java/umc/unimade/domain/accounts/entity/SellerRegister.java
  src/main/java/umc/unimade/domain/products/entity/ProductRegister.java
  src/main/java/umc/unimade/global/registerStatus/RegisterStatus.java
Labels: ✨ Feature, ♻️ Refactor

#33 ♻️ [REFACTOR] id 컬럼명 수정 (#31)
  src/main/java/umc/unimade/domain/accounts/entity/SellerRegister.java
  src/main/java/umc/unimade/domain/products/entity/ProductRegister.java
Labels: ♻️ Refactor

#35 ✨ [FEATURE] 리뷰 (#14)
  src/main/java/umc/unimade/domain/products/dto/ProductResponse.java
  src/main/java/umc/unimade/domain/products/service/strategy/ReviewStrategy.java
  src/main/java/umc/unimade/domain/review/ReviewController.java
  src/main/java/umc/unimade/domain/review/dto/ReviewCreateRequest.java
  src/main/java/umc/unimade/domain/review/dto/ReviewListResponse.java
  src/main/java/umc/unimade/domain/review/dto/ReviewResponse.java
  src/main/java/umc/unimade/domain/review/entity/Review.java
  src/main/java/umc/unimade/domain/review/entity/ReviewImage.java
  src/main/java/umc/unimade/domain/review/service/ReviewCommandService.java
  src/main/java/umc/unimade/domain/review/service/ReviewQueryService.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
  src/main/java/umc/unimade/global/common/exception/ReviewExceptionHandler.java
Labels: ✨ Feature

#38 ✨ [FEATURE] 로그인 개발 (#7)
  src/main/java/umc/unimade/domain/accounts/controller/BuyerController.java
  src/main/java/umc/unimade/domain/accounts/dto/BuyerPageResponse.java
  src/main/java/umc/unimade/domain/accounts/service/BuyerCommandService.java
  src/main/java/umc/unimade/domain/accounts/service/BuyerQueryService.java
  src/main/java/umc/unimade/domain/favorite/dto/FavoriteProductResponse.java
  src/main/java/umc/unimade/domain/favorite/dto/FavoriteSellerResponse.java
  src/main/java/umc/unimade/domain/favorite/repository/FavoriteProductRepository.java
  src/main/java/umc/unimade/domain/favorite/repository/FavoriteSellerRepository.java
Labels: ✨ Feature

#39 ✨ [FEATURE] 판매자 회원가입 승인 요청 처리 및 조회 서비스
  build.gradle
  src/main/java/umc/unimade/domain/accounts/controller/AdminController.java
  src/main/java/umc/unimade/domain/accounts/dto/AdminSellerRegisterRequest.java
  src/main/java/umc/unimade/domain/accounts/dto/AdminSellerRegisterResponse.java
  src/main/java/umc/unimade/domain/accounts/dto/SellerRegisterResponse.java
  src/main/java/umc/unimade/domain/accounts/dto/SellerRegistersResponse.java
  src/main/java/umc/unimade/domain/accounts/entity/SellerRegister.java
  src/main/java/umc/unimade/domain/accounts/exception/BuyerExceptionHandler.java
  src/main/java/umc/unimade/domain/accounts/exception/SellerExceptionHandler.java
  src/main/java/umc/unimade/domain/accounts/repository/SellerRegisterRepository.java
  src/main/java/umc/unimade/domain/accounts/service/SellerRegisterCommandService.java
  src/main/java/umc/unimade/domain/accounts/service/SellerRegisterQueryService.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: ✨ Feature

#41 ✨ [FEATURE] 상품 승인 요청 처리 및 요청 상품 조회 기능 (#40)
  src/main/java/umc/unimade/domain/accounts/controller/SellerRegisterController.java
  src/main/java/umc/unimade/domain/accounts/dto/AdminRegisterRequest.java
  src/main/java/umc/unimade/domain/accounts/service/SellerRegisterCommandService.java
  src/main/java/umc/unimade/domain/products/controller/ProductRegisterController.java
  src/main/java/umc/unimade/domain/products/dto/AdminProductRegisterResponse.java
  src/main/java/umc/unimade/domain/products/dto/ProductRegisterResponse.java
  src/main/java/umc/unimade/domain/products/dto/ProductRegistersResponse.java
  src/main/java/umc/unimade/domain/products/dto/ProductsImageDTO.java
  src/main/java/umc/unimade/domain/products/entity/ProductRegister.java
  src/main/java/umc/unimade/domain/products/entity/ProductsImage.java
  src/main/java/umc/unimade/domain/products/repository/ProductRegisterRepository.java
  src/main/java/umc/unimade/domain/products/service/ProductRegisterCommandService.java
  src/main/java/umc/unimade/domain/products/service/ProductRegisterQueryService.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: ✨ Feature

#47 🐛 [BUG] productRepository 버그 수정 (#46)
  src/main/java/umc/unimade/domain/products/service/ProductRegisterCommandService.java
Labels: 🐛 BugFix

#48 ✨ [FEATURE] 판매자의 상품 등록, 수정, 삭제 구현 (#25)
  src/main/java/umc/unimade/domain/accounts/entity/Seller.java
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
  src/main/java/umc/unimade/domain/products/dto/OptionRequest.java
  src/main/java/umc/unimade/domain/products/dto/ProductRequest.java
  src/main/java/umc/unimade/domain/products/entity/ProductRegister.java
  src/main/java/umc/unimade/domain/products/entity/ProductStatus.java
  src/main/java/umc/unimade/domain/products/entity/Products.java
  src/main/java/umc/unimade/domain/products/entity/ProductsImage.java
  src/main/java/umc/unimade/domain/products/exception/ProductExceptionHandler.java
  src/main/java/umc/unimade/domain/products/repository/CategoryRepository.java
  src/main/java/umc/unimade/domain/products/repository/OptionsRepository.java
  src/main/java/umc/unimade/domain/products/repository/ProductRegisterRepository.java
  src/main/java/umc/unimade/domain/products/repository/ProductsImageRepository.java
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: ✨ Feature

#51 ✨ [FEATURE] 상품 등록/수정 시 options 등록/수정 추가 (#45)
  src/main/java/umc/unimade/domain/orders/repository/OptionValueRepository.java
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
  src/main/java/umc/unimade/domain/products/dto/OptionCategoryRequest.java
  src/main/java/umc/unimade/domain/products/dto/OptionCategoryResponse.java
  src/main/java/umc/unimade/domain/products/dto/OptionRequest.java
  src/main/java/umc/unimade/domain/products/dto/ProductRegisterResponse.java
  src/main/java/umc/unimade/domain/products/dto/ProductRequest.java
  src/main/java/umc/unimade/domain/products/dto/ProductUpdateResponse.java
  src/main/java/umc/unimade/domain/products/entity/OptionCategory.java
  src/main/java/umc/unimade/domain/products/entity/OptionValue.java
  src/main/java/umc/unimade/domain/products/entity/ProductRegister.java
  src/main/java/umc/unimade/domain/products/entity/Products.java
  src/main/java/umc/unimade/domain/products/repository/OptionCategoryRepository.java
  src/main/java/umc/unimade/domain/products/repository/OptionsRepository.java
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
Labels: ✨ Feature

#53 ✨ [FEATURE] 판매자 - 구매 요청 확인(조회) (#42)
  src/main/java/umc/unimade/domain/orders/controller/OrderController.java
  src/main/java/umc/unimade/domain/orders/dto/SellerOrderResponse.java
  src/main/java/umc/unimade/domain/orders/entity/Orders.java
  src/main/java/umc/unimade/domain/orders/entity/ReceiveStatus.java
  src/main/java/umc/unimade/domain/orders/exception/SellerExceptionhandler.java
  src/main/java/umc/unimade/domain/orders/repository/OrderRepository.java
  src/main/java/umc/unimade/domain/orders/service/OrderQueryService.java
Labels: ✨ Feature

#55 :bug: [fix] conflict 해결 (#54)
  src/main/java/umc/unimade/domain/orders/controller/OrderController.java
Labels: 🐛 BugFix

#59 ✨ [FEATURE] 입금 상태, 수령 상태 변경하기 (#44)
  src/main/java/umc/unimade/UnimadeApplication.java
  src/main/java/umc/unimade/domain/orders/controller/OrderController.java
  src/main/java/umc/unimade/domain/orders/entity/OrderStatus.java
  src/main/java/umc/unimade/domain/orders/entity/Orders.java
  src/main/java/umc/unimade/domain/orders/repository/OrderRepository.java
  src/main/java/umc/unimade/domain/orders/service/OrderCommandService.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: ✨ Feature

#60 ✨ [FEATURE] 판매자 마이페이지 구현 (#58)
  src/main/java/umc/unimade/domain/accounts/controller/SellerController.java
  src/main/java/umc/unimade/domain/accounts/dto/SellerMyPageResponse.java
  src/main/java/umc/unimade/domain/accounts/service/SellerQueryService.java
  src/main/java/umc/unimade/domain/orders/dto/SellerOrderResponse.java
  src/main/java/umc/unimade/domain/products/dto/SellingProductResponse.java
  src/main/java/umc/unimade/domain/products/dto/SoldoutProductResponse.java
  src/main/java/umc/unimade/domain/products/repository/ProductRepository.java
Labels: ✨ Feature

#64 ✨ [FEATURE] 판매 상품 리스트 + 필터링 API
  .gitignore
  build.gradle
  src/main/generated/umc/unimade/domain/accounts/entity/QBuyer.java
  src/main/generated/umc/unimade/domain/accounts/entity/QSeller.java
  src/main/generated/umc/unimade/domain/accounts/entity/QSellerRegister.java
  src/main/generated/umc/unimade/domain/favorite/entity/QFavoriteProduct.java
  src/main/generated/umc/unimade/domain/favorite/entity/QFavoriteSeller.java
  src/main/generated/umc/unimade/domain/orders/entity/QOrderItem.java
  src/main/generated/umc/unimade/domain/orders/entity/QOrderOption.java
  src/main/generated/umc/unimade/domain/orders/entity/QOrders.java
  src/main/generated/umc/unimade/domain/orders/entity/QPurchaseForm.java
  src/main/generated/umc/unimade/domain/products/entity/QCategory.java
  src/main/generated/umc/unimade/domain/products/entity/QOptionCategory.java
  src/main/generated/umc/unimade/domain/products/entity/QOptionValue.java
  src/main/generated/umc/unimade/domain/products/entity/QProductRegister.java
  src/main/generated/umc/unimade/domain/products/entity/QProducts.java
  src/main/generated/umc/unimade/domain/products/entity/QProductsImage.java
  src/main/generated/umc/unimade/domain/qna/entity/QAnswerImage.java
  src/main/generated/umc/unimade/domain/qna/entity/QAnswers.java
  src/main/generated/umc/unimade/domain/qna/entity/QQuestionImage.java
  src/main/generated/umc/unimade/domain/qna/entity/QQuestions.java
  src/main/generated/umc/unimade/domain/review/entity/QReview.java
  src/main/generated/umc/unimade/domain/review/entity/QReviewImage.java
  src/main/generated/umc/unimade/global/common/QBaseEntity.java
  src/main/java/umc/unimade/domain/accounts/dto/BuyerOrderHistoryResponse.java
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
  src/main/java/umc/unimade/domain/products/dto/ProductsListResponse.java
  src/main/java/umc/unimade/domain/products/repository/ProductRepository.java
  src/main/java/umc/unimade/domain/products/repository/ProductsRepositoryCustom.java
  src/main/java/umc/unimade/domain/products/repository/ProductsRepositoryCustomImpl.java
  src/main/java/umc/unimade/domain/products/service/ProductsQueryService.java
  src/main/java/umc/unimade/global/config/QueryDSLConfig.java
Labels: ✨ Feature

#66 ♻️ [REFACTOR] 반환값 수정
  .gitignore
  src/main/generated/umc/unimade/domain/accounts/entity/QBuyer.java
  src/main/generated/umc/unimade/domain/accounts/entity/QSeller.java
  src/main/generated/umc/unimade/domain/accounts/entity/QSellerRegister.java
  src/main/generated/umc/unimade/domain/favorite/entity/QFavoriteProduct.java
  src/main/generated/umc/unimade/domain/favorite/entity/QFavoriteSeller.java
  src/main/generated/umc/unimade/domain/orders/entity/QOrderItem.java
  src/main/generated/umc/unimade/domain/orders/entity/QOrderOption.java
  src/main/generated/umc/unimade/domain/orders/entity/QOrders.java
  src/main/generated/umc/unimade/domain/orders/entity/QPurchaseForm.java
  src/main/generated/umc/unimade/domain/products/entity/QCategory.java
  src/main/generated/umc/unimade/domain/products/entity/QOptionCategory.java
  src/main/generated/umc/unimade/domain/products/entity/QOptionValue.java
  src/main/generated/umc/unimade/domain/products/entity/QProductRegister.java
  src/main/generated/umc/unimade/domain/products/entity/QProducts.java
  src/main/generated/umc/unimade/domain/products/entity/QProductsImage.java
  src/main/generated/umc/unimade/domain/qna/entity/QAnswerImage.java
  src/main/generated/umc/unimade/domain/qna/entity/QAnswers.java
  src/main/generated/umc/unimade/domain/qna/entity/QQuestionImage.java
  src/main/generated/umc/unimade/domain/qna/entity/QQuestions.java
  src/main/generated/umc/unimade/domain/review/entity/QReview.java
  src/main/generated/umc/unimade/domain/review/entity/QReviewImage.java
  src/main/generated/umc/unimade/global/common/QBaseEntity.java
  src/main/java/umc/unimade/domain/orders/service/OrderCommandService.java
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
  src/main/java/umc/unimade/domain/products/dto/ProductResponse.java
  src/main/java/umc/unimade/domain/products/service/ProductsQueryService.java
  src/main/java/umc/unimade/domain/products/service/strategy/DetailStrategy.java
  src/main/java/umc/unimade/domain/products/service/strategy/ProductStrategy.java
  src/main/java/umc/unimade/domain/products/service/strategy/QnAStrategy.java
  src/main/java/umc/unimade/domain/products/service/strategy/ReviewStrategy.java
  src/main/java/umc/unimade/domain/qna/controller/QnAController.java
  src/main/java/umc/unimade/domain/qna/dto/AnswerCreateRequest.java
  src/main/java/umc/unimade/domain/qna/dto/AnswerResponse.java
  src/main/java/umc/unimade/domain/qna/dto/QnAListResponse.java
  src/main/java/umc/unimade/domain/qna/dto/QuestionCreateRequest.java
  src/main/java/umc/unimade/domain/qna/dto/QuestionResponse.java
  src/main/java/umc/unimade/domain/qna/repository/QuestionsRepository.java
  src/main/java/umc/unimade/domain/qna/service/QnACommandService.java
  src/main/java/umc/unimade/domain/review/dto/ReviewListResponse.java
  src/main/java/umc/unimade/domain/review/repository/ReviewRepository.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: ♻️ Refactor

#72 ✨ [FEATURE] 상품 수정 승인 요청 처리 (#65)
  .gitignore
  src/main/java/umc/unimade/domain/orders/repository/OptionValueRepository.java
  src/main/java/umc/unimade/domain/products/controller/ProductRegisterController.java
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
  src/main/java/umc/unimade/domain/products/dto/AdminProductRegisterResponse.java
  src/main/java/umc/unimade/domain/products/dto/ProductRegisterResponse.java
  src/main/java/umc/unimade/domain/products/dto/ProductRegistersResponse.java
  src/main/java/umc/unimade/domain/products/dto/ProductRequest.java
  src/main/java/umc/unimade/domain/products/dto/ProductUpdateResponse.java
  src/main/java/umc/unimade/domain/products/entity/OptionCategory.java
  src/main/java/umc/unimade/domain/products/entity/ProductRegister.java
  src/main/java/umc/unimade/domain/products/entity/Products.java
  src/main/java/umc/unimade/domain/products/entity/RegisterType.java
  src/main/java/umc/unimade/domain/products/repository/OptionCategoryRepository.java
  src/main/java/umc/unimade/domain/products/repository/ProductRegisterRepository.java
  src/main/java/umc/unimade/domain/products/repository/ProductsImageRepository.java
  src/main/java/umc/unimade/domain/products/service/ProductRegisterCommandService.java
  src/main/java/umc/unimade/domain/products/service/ProductRegisterQueryService.java
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
Labels: ✨ Feature, ♻️ Refactor

#80 🐛 [BUG] 상품 정보에서 category 테이블 전체가 반환되는 문제 #79
  src/main/java/umc/unimade/domain/products/dto/ProductResponse.java
Labels: 🐛 BugFix

#81 ♻️ [REFACTOR] 요청값 사용자 토큰으로 변경 #70
  src/main/java/umc/unimade/domain/accounts/controller/BuyerController.java
  src/main/java/umc/unimade/domain/accounts/service/BuyerCommandService.java
  src/main/java/umc/unimade/domain/accounts/service/BuyerQueryService.java
  src/main/java/umc/unimade/domain/favorite/repository/FavoriteProductRepository.java
  src/main/java/umc/unimade/domain/favorite/repository/FavoriteSellerRepository.java
  src/main/java/umc/unimade/domain/orders/controller/OrderController.java
  src/main/java/umc/unimade/domain/orders/repository/OrderRepository.java
  src/main/java/umc/unimade/domain/orders/service/OrderCommandService.java
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
  src/main/java/umc/unimade/domain/products/dto/OptionResponse.java
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
  src/main/java/umc/unimade/domain/qna/controller/QnAController.java
  src/main/java/umc/unimade/domain/qna/service/QnACommandService.java
  src/main/java/umc/unimade/domain/review/controller/ReviewController.java
  src/main/java/umc/unimade/domain/review/service/ReviewCommandService.java
Labels: ♻️ Refactor

#83 🐛 [BUG] 상품 목록이 반환되지 않는 문제 #82
  src/main/java/umc/unimade/domain/accounts/controller/BuyerController.java
  src/main/java/umc/unimade/domain/accounts/dto/BuyerPageResponse.java
  src/main/java/umc/unimade/domain/accounts/service/BuyerCommandService.java
  src/main/java/umc/unimade/domain/favorite/repository/FavoriteSellerRepository.java
  src/main/java/umc/unimade/domain/orders/controller/OrderController.java
  src/main/java/umc/unimade/domain/orders/dto/OrderResponse.java
  src/main/java/umc/unimade/domain/orders/entity/OrderItem.java
  src/main/java/umc/unimade/domain/orders/repository/OptionValueRepository.java
  src/main/java/umc/unimade/domain/orders/service/OrderCommandService.java
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
  src/main/java/umc/unimade/domain/products/dto/ProductResponse.java
  src/main/java/umc/unimade/domain/products/dto/ProductsListResponse.java
  src/main/java/umc/unimade/domain/products/repository/ProductsRepositoryCustomImpl.java
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
  src/main/java/umc/unimade/domain/products/service/ProductsQueryService.java
  src/main/java/umc/unimade/domain/qna/controller/QnAController.java
  src/main/java/umc/unimade/domain/qna/dto/AnswerCreateRequest.java
  src/main/java/umc/unimade/domain/qna/dto/AnswerResponse.java
  src/main/java/umc/unimade/domain/qna/dto/QuestionCreateRequest.java
  src/main/java/umc/unimade/domain/qna/dto/QuestionResponse.java
  src/main/java/umc/unimade/domain/qna/entity/Answers.java
  src/main/java/umc/unimade/domain/qna/entity/Questions.java
  src/main/java/umc/unimade/domain/qna/repository/QuestionsRepository.java
  src/main/java/umc/unimade/domain/qna/service/QnACommandService.java
  src/main/java/umc/unimade/domain/review/controller/ReviewController.java
  src/main/java/umc/unimade/domain/review/dto/ReviewListResponse.java
  src/main/java/umc/unimade/domain/review/repository/ReviewRepository.java
  src/main/java/umc/unimade/domain/review/service/ReviewCommandService.java
Labels: 🐛 BugFix

#85 ♻️ [REFACTOR] 관리자 기능 role이 관리자인 사람만 가능하게 하기 (#84)
  src/main/java/umc/unimade/domain/accounts/controller/SellerRegisterController.java
  src/main/java/umc/unimade/domain/products/controller/ProductRegisterController.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
  src/main/java/umc/unimade/global/config/SecurityConfig.java
  src/main/java/umc/unimade/global/security/AdminAccessFilter.java
Labels: ✨ Feature, ♻️ Refactor

#87 🐛 [BUG] 테스트 위해 토큰 정보 제거
  src/main/java/umc/unimade/domain/accounts/repository/BuyerRepository.java
  src/main/java/umc/unimade/domain/orders/controller/OrderController.java
  src/main/java/umc/unimade/domain/orders/service/OrderCommandService.java
Labels: 🐛 BugFix

#92 :bug: [fix] 프로필 이미지 null일 때 처리 (#91)
  src/main/java/umc/unimade/domain/accounts/dto/SellerMyPageResponse.java
Labels: 🐛 BugFix

#93 ✨ [FEATURE] 마이페이지 상품 더보기 구현 (#90)
  src/main/java/umc/unimade/domain/accounts/controller/SellerController.java
  src/main/java/umc/unimade/domain/accounts/dto/SellerMyPageResponse.java
  src/main/java/umc/unimade/domain/accounts/service/SellerQueryService.java
  src/main/java/umc/unimade/domain/orders/controller/OrderController.java
  src/main/java/umc/unimade/domain/orders/repository/OrderRepository.java
  src/main/java/umc/unimade/domain/orders/service/OrderQueryService.java
  src/main/java/umc/unimade/domain/products/dto/MyPageProductResponse.java
  src/main/java/umc/unimade/domain/products/dto/SellingProductResponse.java
Labels: ✨ Feature

#98 ✨ [FEATURE] 리뷰 별점 API #95
  src/main/java/umc/unimade/domain/qna/controller/QnAController.java
  src/main/java/umc/unimade/domain/qna/service/QnACommandService.java
  src/main/java/umc/unimade/domain/review/controller/ReviewController.java
  src/main/java/umc/unimade/domain/review/dto/ReviewCreateRequest.java
  src/main/java/umc/unimade/domain/review/dto/ReviewListResponse.java
  src/main/java/umc/unimade/domain/review/dto/ReviewResponse.java
  src/main/java/umc/unimade/domain/review/entity/Review.java
  src/main/java/umc/unimade/domain/review/service/ReviewCommandService.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: ✨ Feature
