Repository Uni-Made/BE, pull requests merged in 2024-08, with the labels that each got.

#100 ✨ [FEATURE] 리뷰 신고 & 관리자 신고 조회 (#99)
  src/main/java/umc/unimade/domain/review/controller/AdminReviewController.java
  src/main/java/umc/unimade/domain/review/controller/ReviewController.java
  src/main/java/umc/unimade/domain/review/dto/ReviewReportRequest.java
  src/main/java/umc/unimade/domain/review/dto/ReviewReportResponse.java
  src/main/java/umc/unimade/domain/review/dto/ReviewReportsResponse.java
  src/main/java/umc/unimade/domain/review/entity/ReportType.java
  src/main/java/umc/unimade/domain/review/entity/ReviewReport.java
  src/main/java/umc/unimade/domain/review/repository/ReviewReportRepository.java
  src/main/java/umc/unimade/domain/review/service/ReviewCommandService.java
  src/main/java/umc/unimade/domain/review/service/ReviewReportQueryService.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: ✨ Feature

#104 ✨ [FEATURE] 상품 등록/수정하기 수정 (#102)
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
  src/main/java/umc/unimade/domain/products/dto/ProductRequest.java
  src/main/java/umc/unimade/domain/products/entity/PickupOption.java
  src/main/java/umc/unimade/domain/products/entity/ProductRegister.java
  src/main/java/umc/unimade/domain/products/entity/Products.java
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
  src/main/java/umc/unimade/global/common/BaseEntity.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: ✨ Feature

#105 ✨ [FEATURE] QNA 반환값 수정
  src/main/java/umc/unimade/domain/qna/dto/QnAListResponse.java
Labels: ✨ Feature

#110 Feature/#106
  .gitignore
  build.gradle
  src/main/java/umc/unimade/domain/accounts/controller/AuthController.java
  src/main/java/umc/unimade/domain/accounts/dto/SignInRequestDto.java
  src/main/java/umc/unimade/domain/accounts/service/AuthQueryService.java
  src/main/java/umc/unimade/domain/notification/controller/NotificationController.java
  src/main/java/umc/unimade/domain/notification/dto/NotificationRequest.java
  src/main/java/umc/unimade/domain/notification/entity/BuyerNotification.java
  src/main/java/umc/unimade/domain/notification/entity/SellerNotification.java
  src/main/java/umc/unimade/domain/notification/events/AnswerPostedEvent.java
  src/main/java/umc/unimade/domain/notification/repository/FcmTokenRepository.java
  src/main/java/umc/unimade/domain/notification/service/NotificationService.java
  src/main/java/umc/unimade/domain/review/controller/ReviewController.java
  src/main/java/umc/unimade/global/config/FirebaseConfig.java
  src/main/java/umc/unimade/global/util/redis/RedisUtil.java
Labels: ✨ Feature

#109 ✨ [FEATURE] 로그인 Seller Buyer 가져오기 (#108)
  src/main/java/umc/unimade/domain/accounts/entity/Buyer.java
  src/main/java/umc/unimade/domain/accounts/entity/Seller.java
  src/main/java/umc/unimade/domain/accounts/repository/BuyerRepository.java
  src/main/java/umc/unimade/domain/accounts/repository/SellerRepository.java
  src/main/java/umc/unimade/domain/accounts/service/AccountsQueryService.java
  src/main/java/umc/unimade/global/config/WebConfig.java
  src/main/java/umc/unimade/global/security/CustomUserDetail.java
  src/main/java/umc/unimade/global/security/LoginBuyer.java
  src/main/java/umc/unimade/global/security/LoginSeller.java
  src/main/java/umc/unimade/global/security/LoginUserArgumentResolver.java
Labels: ✨ Feature

#113 🌏 [CI]: main.yml firebase key (#112)
  .github/workflows/main.yml
Labels: :earth_asia: Ci

#115 ✨ [FEATURE] 판매자 마이페이지 수정 (#101)
  src/main/java/umc/unimade/domain/accounts/controller/SellerController.java
  src/main/java/umc/unimade/domain/accounts/dto/SellerMyPageResponse.java
  src/main/java/umc/unimade/domain/accounts/dto/SellerPageResponse.java
  src/main/java/umc/unimade/domain/accounts/entity/Seller.java
  src/main/java/umc/unimade/domain/accounts/service/SellerCommandService.java
  src/main/java/umc/unimade/domain/accounts/service/SellerQueryService.java
  src/main/java/umc/unimade/domain/favorite/repository/FavoriteSellerRepository.java
  src/main/java/umc/unimade/domain/orders/controller/OrderController.java
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
Labels: ✨ Feature

#118 ✨ [FEATURE] 상품 등록 시 상세 정보 받기 (#116)
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
  src/main/java/umc/unimade/domain/products/dto/ProductDetailImageDTO.java
  src/main/java/umc/unimade/domain/products/dto/ProductRegisterResponse.java
  src/main/java/umc/unimade/domain/products/dto/ProductUpdateResponse.java
  src/main/java/umc/unimade/domain/products/entity/ProductDetailImage.java
  src/main/java/umc/unimade/domain/products/entity/ProductRegister.java
  src/main/java/umc/unimade/domain/products/entity/Products.java
  src/main/java/umc/unimade/domain/products/repository/ProductDetailImageRepository.java
  src/main/java/umc/unimade/domain/products/service/ProductRegisterCommandService.java
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
Labels: ✨ Feature

#120 ✨ [FEATURE] 주문 시 수령 방법에 따른 응답 구조 변경
  src/main/java/umc/unimade/domain/accounts/controller/BuyerController.java
  src/main/java/umc/unimade/domain/accounts/service/BuyerQueryService.java
  src/main/java/umc/unimade/domain/notification/service/NotificationService.java
  src/main/java/umc/unimade/domain/orders/dto/BuyerOrderHistoryResponse.java
  src/main/java/umc/unimade/domain/orders/dto/OrderStatusDetailResponse.java
  src/main/java/umc/unimade/domain/orders/entity/OrderItem.java
  src/main/java/umc/unimade/domain/orders/entity/Orders.java
  src/main/java/umc/unimade/domain/orders/service/OrderCommandService.java
  src/main/java/umc/unimade/domain/products/dto/ProductDetailResponse.java
  src/main/java/umc/unimade/domain/products/dto/ProductResponse.java
  src/main/java/umc/unimade/domain/products/repository/ProductsRepositoryCustomImpl.java
  src/main/java/umc/unimade/domain/products/service/strategy/DetailStrategy.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: 🐛 BugFix, ✨ Feature

#126 🐛[FIX] 리뷰 작성 API 수정 #122
  src/main/java/umc/unimade/domain/orders/entity/Orders.java
  src/main/java/umc/unimade/domain/review/controller/ReviewController.java
  src/main/java/umc/unimade/domain/review/dto/ReviewCreateRequest.java
  src/main/java/umc/unimade/domain/review/dto/ReviewListResponse.java
  src/main/java/umc/unimade/domain/review/entity/Review.java
  src/main/java/umc/unimade/domain/review/service/ReviewCommandService.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: 🐛 BugFix

#128 ♻️ [REFACTOR] swagger 링크 허용 (#127)
  src/main/java/umc/unimade/global/config/SecurityConfig.java
Labels: ♻️ Refactor

#130 ✨ [FEATURE] 구매 완료 알림 #121
  src/main/java/umc/unimade/domain/notification/events/OrderRequestEvent.java
  src/main/java/umc/unimade/domain/notification/service/NotificationService.java
  src/main/java/umc/unimade/domain/orders/service/OrderCommandService.java
  src/main/java/umc/unimade/global/config/FirebaseConfig.java
Labels: ✨ Feature

#132 ♻️ [REFACTOR] 사용자 신고 유저 연결 (#123)
  src/main/java/umc/unimade/domain/review/controller/ReviewController.java
  src/main/java/umc/unimade/domain/review/service/ReviewCommandService.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: ♻️ Refactor

#137 🐛 [FIX] 입금 남은 날 알려주기 #136
  src/main/java/umc/unimade/domain/notification/service/NotificationService.java
Labels: 🐛 BugFix

#141 ✨ [FEATURE] 온라인 수령 시 배송예정일자 추가 #140
  src/main/java/umc/unimade/domain/orders/dto/OrderStatusDetailResponse.java
Labels: ✨ Feature

#143 ✨ [FEATURE] categoryId요청 형식 변경 #69
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
  src/main/java/umc/unimade/domain/products/repository/ProductsRepositoryCustom.java
  src/main/java/umc/unimade/domain/products/repository/ProductsRepositoryCustomImpl.java
  src/main/java/umc/unimade/domain/products/service/ProductsQueryService.java
Labels: ✨ Feature

#144 :bug: [FIX] @LoginBuyer로 buyer정보 받아오기
  src/main/java/umc/unimade/domain/accounts/service/AccountsQueryService.java
  src/main/java/umc/unimade/domain/accounts/service/AuthCommandService.java
  src/main/java/umc/unimade/domain/notification/service/NotificationService.java
  src/main/java/umc/unimade/domain/orders/service/OrderCommandService.java
  src/main/java/umc/unimade/global/security/LoginUserArgumentResolver.java
  src/main/java/umc/unimade/global/util/redis/RedisUtil.java
Labels: ✨ Feature

#147 ✨ [FEATURE] 메이더 홈 수정 (#89)
  src/main/java/umc/unimade/domain/accounts/controller/BuyerController.java
  src/main/java/umc/unimade/domain/accounts/controller/SellerController.java
  src/main/java/umc/unimade/domain/accounts/dto/SellerPageResponse.java
  src/main/java/umc/unimade/domain/accounts/service/BuyerQueryService.java
  src/main/java/umc/unimade/domain/accounts/service/SellerCommandService.java
  src/main/java/umc/unimade/domain/accounts/service/SellerQueryService.java
  src/main/java/umc/unimade/domain/favorite/repository/FavoriteSellerRepository.java
  src/main/java/umc/unimade/domain/orders/controller/OrderController.java
  src/main/java/umc/unimade/domain/orders/service/OrderQueryService.java
  src/main/java/umc/unimade/domain/products/controller/ProductsController.java
  src/main/java/umc/unimade/domain/products/dto/ProductRequest.java
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
Labels: ✨ Feature

#152 ✨ [FEATURE] 관리자 공지 게시판 (#135)
  src/main/java/umc/unimade/domain/noticeBoard/controller/NoticeBoardController.java
  src/main/java/umc/unimade/domain/noticeBoard/dto/NoticeBoardRequest.java
  src/main/java/umc/unimade/domain/noticeBoard/dto/NoticeBoardResponse.java
  src/main/java/umc/unimade/domain/noticeBoard/dto/NoticeBoardsResponse.java
  src/main/java/umc/unimade/domain/noticeBoard/entity/NoticeBoard.java
  src/main/java/umc/unimade/domain/noticeBoard/exception/NoticeBoardExceptionHandler.java
  src/main/java/umc/unimade/domain/noticeBoard/repository/NoticeBoardRepository.java
  src/main/java/umc/unimade/domain/noticeBoard/service/NoticeBoardCommandService.java
  src/main/java/umc/unimade/domain/noticeBoard/service/NoticeBoardQueryService.java
  src/main/java/umc/unimade/domain/review/controller/AdminReviewController.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
  src/main/java/umc/unimade/global/config/SecurityConfig.java
  src/main/java/umc/unimade/global/security/AdminAccessFilter.java
Labels: ✨ Feature

#154 ♻️ [REFACTOR] S3 파일 확장자 같이 붙이게 수정 (#153)
  src/main/java/umc/unimade/global/util/s3/S3Provider.java
Labels: ♻️ Refactor

#158 ✨ [FEATURE] 판매자 마이페이지 상품 상세 보기 (#151)
  src/main/java/umc/unimade/domain/accounts/controller/SellerController.java
  src/main/java/umc/unimade/domain/accounts/service/SellerQueryService.java
  src/main/java/umc/unimade/domain/qna/dto/QuestionResponse.java
  src/main/java/umc/unimade/domain/qna/repository/QuestionsRepository.java
Labels: ✨ Feature

#159 ✨ [FEATURE] 리뷰 답변하기 (#149)
  src/main/java/umc/unimade/domain/accounts/controller/SellerController.java
  src/main/java/umc/unimade/domain/accounts/entity/Seller.java
  src/main/java/umc/unimade/domain/accounts/service/SellerQueryService.java
  src/main/java/umc/unimade/domain/review/controller/ReviewController.java
  src/main/java/umc/unimade/domain/review/dto/ReviewAnswerCreateRequest.java
  src/main/java/umc/unimade/domain/review/dto/ReviewAnswerResposne.java
  src/main/java/umc/unimade/domain/review/dto/ReviewResponse.java
  src/main/java/umc/unimade/domain/review/entity/Review.java
  src/main/java/umc/unimade/domain/review/entity/ReviewAnswer.java
  src/main/java/umc/unimade/domain/review/repository/ReviewAnswerRepository.java
  src/main/java/umc/unimade/domain/review/repository/ReviewRepository.java
  src/main/java/umc/unimade/domain/review/service/ReviewCommandService.java
Labels: ✨ Feature

#162 :bug: [FIX] 상품구매하기가 Transaction Rollback 되는 문제
  src/main/java/umc/unimade/domain/orders/controller/BuyerOrderController.java
  src/main/java/umc/unimade/domain/orders/service/OrderQueryService.java
Labels: 🐛 BugFix

#164 ✨ [FEATURE] 판매자 알림 (#148)
  src/main/java/umc/unimade/domain/notification/controller/NotificationController.java
  src/main/java/umc/unimade/domain/notification/dto/SellerNotificationListResponse.java
  src/main/java/umc/unimade/domain/notification/entity/SellerNotification.java
  src/main/java/umc/unimade/domain/notification/events/OrderedEvent.java
  src/main/java/umc/unimade/domain/notification/events/QuestionPostedEvent.java
  src/main/java/umc/unimade/domain/notification/events/ReviewPostedEvent.java
  src/main/java/umc/unimade/domain/notification/repository/SellerNotificationRepository.java
  src/main/java/umc/unimade/domain/notification/service/NotificationService.java
  src/main/java/umc/unimade/domain/notification/service/SellerNotificationService.java
  src/main/java/umc/unimade/domain/orders/dto/OrderStatusDetailResponse.java
  src/main/java/umc/unimade/domain/orders/entity/PurchaseForm.java
  src/main/java/umc/unimade/domain/orders/repository/OrderRepository.java
  src/main/java/umc/unimade/domain/orders/service/OrderCommandService.java
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
  src/main/java/umc/unimade/domain/qna/service/QnACommandService.java
  src/main/java/umc/unimade/domain/review/service/ReviewCommandService.java
Labels: ✨ Feature

#166 :bug: fix : 커서기반 페이지네이션에서 오프셋 기반 페이지네이션으로 수정
  src/main/java/umc/unimade/domain/products/controller/BuyerProductController.java
  src/main/java/umc/unimade/domain/products/dto/ProductsListResponse.java
  src/main/java/umc/unimade/domain/products/entity/SortType.java
  src/main/java/umc/unimade/domain/products/repository/ProductsRepositoryCustom.java
  src/main/java/umc/unimade/domain/products/repository/ProductsRepositoryCustomImpl.java
  src/main/java/umc/unimade/domain/products/service/ProductsQueryService.java
Labels: 🐛 BugFix

#167 :bug: [FIX] transactionRoll
  src/main/java/umc/unimade/domain/accounts/entity/Buyer.java
  src/main/java/umc/unimade/domain/notification/entity/BuyerNotification.java
Labels: 🐛 BugFix

#170 🐛 [FIX] 상품 구매 시 트랜잭션 오류 발생 #168
  src/main/java/umc/unimade/domain/notification/service/BuyerNotificationService.java
Labels: 🐛 BugFix

#172 🐛 [FIX] 답변에서 title 제거
  src/main/java/umc/unimade/domain/qna/dto/AnswerCreateRequest.java
  src/main/java/umc/unimade/domain/qna/dto/AnswerResponse.java
  src/main/java/umc/unimade/domain/qna/dto/QnAListResponse.java
  src/main/java/umc/unimade/domain/qna/entity/Answers.java
Labels: 🐛 BugFix

#174 :bug: [FIX] productResponse 수정
  src/main/java/umc/unimade/domain/products/dto/ProductResponse.java
Labels: 🐛 BugFix

#176 ♻️ [REFACTOR] 공지 정렬 & 검색 기능 (#175)
  src/main/java/umc/unimade/domain/noticeBoard/controller/NoticeBoardController.java
  src/main/java/umc/unimade/domain/noticeBoard/repository/NoticeBoardRepository.java
  src/main/java/umc/unimade/domain/noticeBoard/service/NoticeBoardQueryService.java
Labels: ✨ Feature, ♻️ Refactor

#182 :recycle: [REFACTOR] 상품 수정 api patch로 변경 (#181)
  src/main/java/umc/unimade/domain/products/controller/SellerProductController.java
Labels: ♻️ Refactor

#185 :recycle: [REFACTOR] detailImage null도 가능하게 수정 (#184)
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
Labels: ♻️ Refactor

#187 :recycle: [REFACTOR] 상품 정보 반환값에 은행 정보 추가 (#186)
  src/main/java/umc/unimade/domain/products/dto/ProductResponse.java
Labels: ♻️ Refactor

#189 ♻️ [REFACTOR] ProductRegister enum 수정 (#188)
  src/main/java/umc/unimade/domain/products/entity/ProductRegister.java
Labels: ♻️ Refactor

#191 ♻️ [REFACTOR] 상품 - 자신의 상품이 아닌경우 에외처리 (#190)
  src/main/java/umc/unimade/domain/products/controller/SellerProductController.java
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
  src/main/java/umc/unimade/global/common/ErrorCode.java
Labels: ♻️ Refactor

#194 [REFACTOR] 상품 수정시 이미지 관리 (#193)
  src/main/java/umc/unimade/domain/products/service/ProductsCommandService.java
Labels: 🐛 BugFix, ♻️ Refactor
